### ISSUE TITLE
`#key = new Uint8Array(1);` line is actually unnecessary. Because a new value is always assigned to the constructor.

### ISSUE THREAD

**Issue by virjilakrum** [fybx/zkl-kds#2]
https://github.com/fybx/zkl-kds/blob/ca521e033f6e4434d336b6fd9e8e2f4f3cb11bee/key.js#L5

**Comment by virjilakrum** [comment]
@fybx

**Comment by itsyigid** [comment]
it's there so linters can deduce the type

**Comment by virjilakrum** [comment]
![cbe8e2ef-dbeb-44b6-b5c5-db92597788e5](https://github.com/user-attachments/assets/c0116d85-f8de-44b4-967b-0351ec885306)
